openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: Local development server
  - url: https://task-api-61wh.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task-related enpoints
paths:
  /tasks:
    $ref: paths/tasks.yaml
  /tasks/{id}:
    $ref: paths/taskById.yaml
